# -*- coding: utf-8 -*-
"""Text_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpEj_ueeYCMDTUUvHYXSFu_2nomzY940
"""

!pip install transformers sentencepiece

from transformers import pipeline

# Load BART summarization model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# User input text
text = input("Enter the text you want to summarize:\n\n")

# Generate summary
summary = summarizer(text, max_length=80, min_length=20, do_sample=False)

print("\nSummary:\n", summary[0]['summary_text'])